#!/usr/bin/env python3
"""Cross-platform Maker Kit asset/schema test for macOS, Windows and Linux CI."""

from __future__ import annotations

import os
from pathlib import Path
import shutil
import subprocess
import tempfile


ROOT = Path(__file__).resolve().parents[1]
FIXTURE = ROOT / "tests" / "fixtures" / "maker_clean_project"
GODOT = os.environ.get("GODOT", "godot")


def run(args: list[str], cwd: Path, home: Path, log_name: str) -> None:
    env = os.environ.copy()
    env["HOME"] = str(home)
    command = [GODOT, "--headless", "--quiet", "--log-file", str(home / log_name), *args]
    completed = subprocess.run(command, cwd=cwd, env=env, text=True, capture_output=True)
    if completed.returncode != 0:
        raise RuntimeError(
            f"command failed ({completed.returncode}): {command}\n"
            f"stdout:\n{completed.stdout}\nstderr:\n{completed.stderr}"
        )


def copy_file(source: Path, target: Path) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, target)


def snapshot(directory: Path) -> dict[str, bytes]:
    return {
        path.relative_to(directory).as_posix(): path.read_bytes()
        for path in sorted(directory.rglob("*"))
        if path.is_file()
    }


def main() -> None:
    with tempfile.TemporaryDirectory(prefix="vrweb-maker-portability-") as temp:
        work = Path(temp)
        home = work / "home"
        project = work / "project"
        home.mkdir()
        project.mkdir()

        for name in ("project.godot", "asset_test.gd", "asset_test.tscn"):
            copy_file(FIXTURE / name, project / name)
        shutil.copytree(FIXTURE / "asset_fixtures", project / "asset_fixtures")
        shutil.copytree(ROOT / "addons" / "vrweb_tools", project / "addons" / "vrweb_tools")
        copy_file(ROOT / "templates" / "vrweb_maker_starter" / "world.tscn",
                  project / "world.tscn")
        copy_file(ROOT / "templates" / "vrweb_maker_starter" / "assets" / "starter-image.svg",
                  project / "assets" / "starter-image.svg")
        copy_file(ROOT / "schemas" / "vrweb-html-data.json",
                  project / "schemas" / "vrweb-html-data.json")

        run(["--path", str(project), "--import"], project, home, "import.log")
        # The committed completion data must be byte-identical to the vocabulary generated by
        # this platform's Godot ClassDB, without loading any Knossos-only project dependencies.
        run(
            [
                "--path",
                str(project),
                "--script",
                "res://addons/vrweb_tools/vrweb_schema_cli.gd",
                "--",
                "--output=res://schemas/vrweb-html-data.json",
                "--check",
            ],
            project,
            home,
            "schema.log",
        )
        # The scene verifies glTF rewriting, missing paths and exact-case rejection even on
        # case-insensitive filesystems.
        run(["--path", str(project), "res://asset_test.tscn"], project, home, "assets.log")

        cli = [
            "--path",
            str(project),
            "--script",
            "res://addons/vrweb_tools/vrweb_cli.gd",
            "--",
            "--scene=res://world.tscn",
            "--output=res://dist/world.html",
            "--profile=strict",
            "--mode=exclusive",
            "--report=res://dist/report.json",
        ]
        run(cli, project, home, "build-first.log")
        first = snapshot(project / "dist")
        if not first or "world.html" not in first or "world.assets.json" not in first:
            raise RuntimeError("strict build did not create the expected portable dist")
        run(cli, project, home, "build-second.log")
        second = snapshot(project / "dist")
        if first != second:
            changed = sorted(set(first) ^ set(second) | {
                name for name in set(first) & set(second) if first[name] != second[name]
            })
            raise RuntimeError(f"Maker Kit dist is not deterministic: {changed}")

    print("maker portability: PASSED")


if __name__ == "__main__":
    main()
