#!/usr/bin/env python3
"""Generate the language-neutral SDK package and typed JS catalog from normative specs."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
SPEC = ROOT / "spec"
SDK_WIT = ROOT / "sdk" / "wit"
JS_GENERATED = ROOT / "sdk" / "javascript" / "generated"
SDK_VERSION = "1.0.0"


def outputs() -> dict[Path, bytes]:
    generated: dict[Path, bytes] = {}
    for package_dir in sorted((SPEC / "wit").iterdir()):
        for source in sorted(package_dir.glob("*.wit")):
            if package_dir.name == "vrweb-module":
                target = SDK_WIT / source.name
            else:
                target = SDK_WIT / "deps" / package_dir.name / source.name
            generated[target] = source.read_bytes()

    catalog = json.loads((SPEC / "scene-api-catalog.json").read_text(encoding="utf-8"))
    methods = sorted(
        f"{class_name}.{method_name}"
        for class_name, entries in catalog["methods"].items()
        for method_name in entries
    )
    signals = sorted(
        f"{class_name}.{signal_name}"
        for class_name, entries in catalog["signals"].items()
        for signal_name in entries
    )
    js = (
        "// Generated by tools/generate_wasm_sdk.py; do not edit.\n"
        f"export const sdkVersion = {json.dumps(SDK_VERSION)};\n"
        f"export const sceneCatalog = {json.dumps(catalog, sort_keys=True, separators=(',', ':'))};\n"
    )
    method_type = " | ".join(json.dumps(item) for item in methods) or "never"
    signal_type = " | ".join(json.dumps(item) for item in signals) or "never"
    declarations = (
        "// Generated by tools/generate_wasm_sdk.py; do not edit.\n"
        f"export declare const sdkVersion: {json.dumps(SDK_VERSION)};\n"
        f"export type SceneMethod = {method_type};\n"
        f"export type SceneSignal = {signal_type};\n"
        "export declare const sceneCatalog: Readonly<Record<string, unknown>>;\n"
    )
    generated[JS_GENERATED / "catalog.js"] = js.encode()
    generated[JS_GENERATED / "catalog.d.ts"] = declarations.encode()
    generated[ROOT / "sdk" / "sdk.json"] = (
        json.dumps(
            {
                "format": 1,
                "version": SDK_VERSION,
                "world": "vrweb:module@1",
                "scene_catalog": "../spec/scene-api-catalog.json",
            },
            indent=2,
        )
        + "\n"
    ).encode()
    return generated


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale: list[str] = []
    for path, content in outputs().items():
        if args.check:
            if not path.is_file() or path.read_bytes() != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content)
    if stale:
        print("generated WASM SDK is stale: " + ", ".join(stale), file=sys.stderr)
        return 1
    print("WASM SDK generation check: PASS" if args.check else "WASM SDK generated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
